[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 26

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/img/:key"
  to = "/.netlify/images?url=/uploads/:key"
  status = 200
